// <auto-generated />
using System;
using ContosoDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContosoDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ContosoDashboard.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            AnnouncementId = 1,
                            Content = "Welcome to the new ContosoDashboard application. This platform will help you manage your tasks and projects more efficiently.",
                            CreatedByUserId = 1,
                            ExpiryDate = new DateTime(2026, 7, 12, 22, 43, 41, 525, DateTimeKind.Utc).AddTicks(2627),
                            IsActive = true,
                            PublishDate = new DateTime(2026, 6, 12, 22, 43, 41, 525, DateTimeKind.Utc).AddTicks(2150),
                            Title = "Welcome to ContosoDashboard"
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ProjectId", "UploadedAtUtc");

                    b.HasIndex("UploadedByUserId", "UploadedAtUtc");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAtUtc");

                    b.HasIndex("DocumentId", "OccurredAtUtc");

                    b.ToTable("DocumentAuditLogs", (string)null);
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipientTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("DocumentId", "RecipientUserId");

                    b.ToTable("DocumentShares", (string)null);
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Value")
                        .IsUnique();

                    b.ToTable("DocumentTags", (string)null);
                });

            modelBuilder.Entity("ContosoDashboard.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TargetCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("Status");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CreatedDate = new DateTime(2026, 5, 13, 22, 43, 41, 523, DateTimeKind.Utc).AddTicks(7758),
                            Description = "Internal employee productivity dashboard",
                            Name = "ContosoDashboard Development",
                            ProjectManagerId = 2,
                            StartDate = new DateTime(2026, 5, 13, 22, 43, 41, 523, DateTimeKind.Utc).AddTicks(6354),
                            Status = 1,
                            TargetCompletionDate = new DateTime(2026, 8, 11, 22, 43, 41, 523, DateTimeKind.Utc).AddTicks(6829),
                            UpdatedDate = new DateTime(2026, 6, 12, 22, 43, 41, 523, DateTimeKind.Utc).AddTicks(8196)
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectMemberId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectMemberId = 1,
                            AssignedDate = new DateTime(2026, 5, 13, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(8417),
                            ProjectId = 1,
                            Role = "TeamLead",
                            UserId = 3
                        },
                        new
                        {
                            ProjectMemberId = 2,
                            AssignedDate = new DateTime(2026, 5, 13, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(8862),
                            ProjectId = 1,
                            Role = "Developer",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DueDate");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 5, 13, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(4224),
                            Description = "Create entity relationship diagram and database design",
                            DueDate = new DateTime(2026, 5, 23, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(2311),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 2,
                            Title = "Design database schema",
                            UpdatedDate = new DateTime(2026, 5, 23, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(4736)
                        },
                        new
                        {
                            TaskId = 2,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 5, 18, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(5148),
                            Description = "Set up Microsoft Entra ID authentication",
                            DueDate = new DateTime(2026, 6, 17, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(5144),
                            Priority = 3,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Implement authentication",
                            UpdatedDate = new DateTime(2026, 6, 12, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(5149)
                        },
                        new
                        {
                            TaskId = 3,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 5, 23, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(5154),
                            Description = "Design user interface mockups for all main pages",
                            DueDate = new DateTime(2026, 6, 22, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(5152),
                            Priority = 1,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Create UI mockups",
                            UpdatedDate = new DateTime(2026, 5, 23, 22, 43, 41, 524, DateTimeKind.Utc).AddTicks(5155)
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InAppNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 6, 12, 22, 43, 41, 522, DateTimeKind.Utc).AddTicks(792),
                            Department = "IT",
                            DisplayName = "System Administrator",
                            Email = "admin@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Administrator",
                            Role = 3
                        },
                        new
                        {
                            UserId = 2,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 6, 12, 22, 43, 41, 522, DateTimeKind.Utc).AddTicks(2019),
                            Department = "Engineering",
                            DisplayName = "Camille Nicole",
                            Email = "camille.nicole@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Project Manager",
                            Role = 2
                        },
                        new
                        {
                            UserId = 3,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 6, 12, 22, 43, 41, 522, DateTimeKind.Utc).AddTicks(2024),
                            Department = "Engineering",
                            DisplayName = "Floris Kregel",
                            Email = "floris.kregel@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Team Lead",
                            Role = 1
                        },
                        new
                        {
                            UserId = 4,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 6, 12, 22, 43, 41, 522, DateTimeKind.Utc).AddTicks(2028),
                            Department = "Engineering",
                            DisplayName = "Ni Kang",
                            Email = "ni.kang@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Software Engineer",
                            Role = 0
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.Announcement", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Document", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContosoDashboard.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentAuditLog", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.Document", "Document")
                        .WithMany("AuditLogs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentShare", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Document", "Document")
                        .WithMany("Shares")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("GrantedByUser");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentTag", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Document", "Document")
                        .WithMany("Tags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Notification", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("ContosoDashboard.Models.ProjectMember", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskComment", b =>
                {
                    b.HasOne("ContosoDashboard.Models.TaskItem", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Document", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Shares");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ContosoDashboard.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTasks");

                    b.Navigation("ManagedProjects");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
